---
title: "Wrangling"
author: "Takudzwanashe Michael Mhuru"
date: "2023-10-16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load packages
library(ggplot2)
library(mdsr)
library(tidyverse)
library(Stat2Data)
library(dplyr)
library(lubridate)
library(janitor)
library(readr)
```

# READ DATA
```{r, eval=FALSE}
#read files 
cast <- readr::read_tsv('/Users/taku_mh/Documents/GitHub/Movie-Reccomendation-System/data/cast.tsv')

ratings <- readr::read_tsv('/Users/taku_mh/Documents/GitHub/Movie-Reccomendation-System/data/ratings.tsv')

title <- readr::read_tsv('/Users/taku_mh/Documents/GitHub/Movie-Reccomendation-System/data/title.tsv')

movies <- readr::read_tsv('/Users/taku_mh/Documents/GitHub/Movie-Reccomendation-System/data/movies.tsv', show_col_types = FALSE)
```

# SELECT AND DROP COLUMNS

```{r, eval=FALSE}
#select relevant columns
ratings <- 
  ratings %>% 
  select(tconst, averageRating)

#view all the unique title groups
print(unique(title$titleType))

#remove videoGame titles
title_clean <- 
  subset(title, titleType!="videoGame")

#confirm that removal has occured
print(unique(title_clean$titleType))

#reduce movie data to title 
movie_clean <- movies %>% 
  filter(ordering %in% c("1"))

title_clean <- title_clean %>% 
  rename("titleId" = "tconst")

#create a joined movie_df
merged_movies <- merge(movie_clean, title_clean, by="titleId")

```
#create csvs

```{r, eval=FALSE}
#write movie csv
write.csv(merged_movies,
     file = "/Users/taku_mh/Documents/GitHub/Movie-Reccomendation-System/data/movies.csv",
     row.names = FALSE)

#write ratings csv
write.csv(ratings,
     file = "/Users/taku_mh/Documents/GitHub/Movie-Reccomendation-System/data/ratings.csv",
     row.names = FALSE)

#write cast csv
write.csv(cast,
     file = "/Users/taku_mh/Documents/GitHub/Movie-Reccomendation-System/data/cast.csv",
     row.names = FALSE)
```

#load csvs

```{r}
movie <- read.csv("data/movies.csv")
casts <- read.csv("data/cast.csv")
rating <- read.csv("data/ratings.csv")
```

#rename columns
```{r}
#movies
movie <-
  movie %>% 
  select(titleId,
         region,
         language,
         types,
         primaryTitle,
         isAdult,
         startYear,
         runtimeMinutes,
         genres) %>% 
  rename("title" = "primaryTitle",
         "year" = "startYear",
         "runtime" = "runtimeMinutes",
         "movieId" = "titleId")

#cast
casts <-
  casts %>% 
  rename("castId" = "nconst",
         "roles" = "primaryProfession",
         "movies" = "knownForTitles")
```

# get all unique values
```{r}
genres <-
  unique(unlist(strsplit(as.character(movie$genres), ",")))

genres

roles <-
  unique(unlist(strsplit(as.character(casts$roles), ",")))

roles
```

#update csvs
```{r}
#write movie csv
write.csv(movie,
     file = "/Users/taku_mh/Documents/GitHub/Movie-Reccomendation-System/data/movies.csv",
     row.names = FALSE)

#write cast csv
write.csv(casts,
     file = "/Users/taku_mh/Documents/GitHub/Movie-Reccomendation-System/data/cast.csv",
     row.names = FALSE)
```
